### ISSUE TITLE
Mod not working on the server: `RuntimeException: Attempted to load class com/tttsaurus/fluidintetweaker/client/jefi/impl/JEFIPlugin for invalid side SERVER`

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#8]
Im using `FITweaker.addRecipe` to add recipes. Its working fine on the client, but not working on server.

`crafttweaker.log` error:
```less
[INITIALIZATION][SERVER][FATAL] Failed to apply this action
java.lang.NoClassDefFoundError: com/tttsaurus/fluidintetweaker/client/jefi/impl/JEFIPlugin
	at com.tttsaurus.fluidintetweaker.common.impl.interaction.FluidInteractionRecipeManager.addRecipe(FluidInteractionRecipeManager.java:77)
	at com.tttsaurus.fluidintetweaker.wrapper.crt.impl.FITActions$AddRecipesAction.apply(FITActions.java:142)
	at youyihj.zenutils.impl.runtime.ZenUtilsTweaker.apply(ZenUtilsTweaker.java:58)
	at crafttweaker.CraftTweakerAPI.apply(MixinCraftTweakerAPI.java:151)
	at com.tttsaurus.fluidintetweaker.wrapper.crt.impl.FITweaker.addRecipe(FITweaker.java:67)
	at category\Fluids.__script__(category/fluids.zs:62)
	at __ZenMain__.run(category\Fluids)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
        [...]
Caused by: java.lang.ClassNotFoundException: com.tttsaurus.fluidintetweaker.client.jefi.impl.JEFIPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 24 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@64aeaf29 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 26 more
Caused by: java.lang.RuntimeException: Attempted to load class com/tttsaurus/fluidintetweaker/client/jefi/impl/JEFIPlugin for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 28 more
```

**Comment by tttsaurus** [comment]
pls try the latest action build

**Comment by Krutoy242** [comment]
I will try later.

**Comment by Krutoy242** [comment]
Yes, with latest action build crash doesnt happens.

**Comment by Krutoy242** [comment]
Answering [this comment](https://github.com/tttsaurus/Fluid-Interaction-Tweaker/issues/4#issuecomment-2529686114):
Oh, sorry, i accidentally commented wrong issue. Im talking about this fix.
